"""
ForensicAI — Module 4: AI-Generated Image Detection

Classifies whether an image is a real photograph or generated by an AI model
(GAN, Diffusion model, etc.). Uses EfficientNet-B0 with transfer learning.

Includes Grad-CAM visualization to show which regions the model focused on
for its decision — demonstrating Explainable AI (XAI).

Two modes:
    - Trained mode: Uses a fine-tuned model checkpoint.
    - Fallback mode: Uses pretrained ImageNet features + statistical analysis
      to provide a demonstration when no trained model is available.
"""

import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms, models
from typing import Optional

from forensics.base import BaseAnalyzer, AnalysisResult
from app.config import AI_INPUT_SIZE, AI_CONFIDENCE_THRESHOLD, AI_MODEL_PATH
from utils.image_utils import image_to_base64, bgr_to_rgb
from utils.visualization import overlay_heatmap


class GradCAM:
    """Grad-CAM implementation for CNN explainability."""

    def __init__(self, model: nn.Module, target_layer: nn.Module):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None

        # Register hooks
        target_layer.register_forward_hook(self._forward_hook)
        target_layer.register_backward_hook(self._backward_hook)

    def _forward_hook(self, module, input, output):
        self.activations = output.detach()

    def _backward_hook(self, module, grad_input, grad_output):
        self.gradients = grad_output[0].detach()

    def generate(self, input_tensor: torch.Tensor, target_class: Optional[int] = None) -> np.ndarray:
        self.model.eval()
        output = self.model(input_tensor)

        if target_class is None:
            target_class = output.argmax(dim=1).item()

        self.model.zero_grad()
        one_hot = torch.zeros_like(output)
        one_hot[0, target_class] = 1.0
        output.backward(gradient=one_hot)

        # Pool gradients across spatial dimensions
        weights = self.gradients.mean(dim=(2, 3), keepdim=True)

        # Weighted combination of activation maps
        cam = (weights * self.activations).sum(dim=1, keepdim=True)
        cam = F.relu(cam)

        # Normalize
        cam = cam.squeeze().cpu().numpy()
        cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

        return cam


class AIDetector(BaseAnalyzer):

    def __init__(self):
        self.device = torch.device("cpu")
        self.model = None
        self.grad_cam = None
        self.transform = transforms.Compose([
            transforms.ToPILImage(),
            transforms.Resize((AI_INPUT_SIZE, AI_INPUT_SIZE)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ])
        self._initialized = False

    def _initialize(self):
        """Lazy initialization of the model."""
        if self._initialized:
            return

        self.model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)

        # Replace classifier for binary classification
        num_features = self.model.classifier[1].in_features
        self.model.classifier = nn.Sequential(
            nn.Dropout(p=0.2, inplace=True),
            nn.Linear(num_features, 2),
        )

        # Try to load trained weights
        self._trained = False
        if AI_MODEL_PATH.exists():
            try:
                state_dict = torch.load(AI_MODEL_PATH, map_location=self.device, weights_only=True)
                self.model.load_state_dict(state_dict)
                self._trained = True
            except Exception:
                pass  # Fall back to pretrained features

        self.model.to(self.device)
        self.model.eval()

        # Set up Grad-CAM on the last convolutional layer
        target_layer = self.model.features[-1]
        self.grad_cam = GradCAM(self.model, target_layer)

        self._initialized = True

    @property
    def name(self) -> str:
        return "ai_detection"

    @property
    def display_name(self) -> str:
        return "AI-Generated Image Detection"

    @property
    def description(self) -> str:
        return "Classifies whether an image is real or AI-generated using deep learning with Grad-CAM explainability."

    def analyze(self, image: np.ndarray, image_path=None) -> AnalysisResult:
        self._initialize()

        rgb = bgr_to_rgb(image)
        input_tensor = self.transform(rgb).unsqueeze(0).to(self.device)

        # ── Forward pass ────────────────────────────────────────────────
        with torch.set_grad_enabled(True):
            input_tensor.requires_grad_(True)
            output = self.model(input_tensor)
            probs = F.softmax(output, dim=1)

        prob_real = probs[0, 0].item()
        prob_ai = probs[0, 1].item()

        # ── Grad-CAM ───────────────────────────────────────────────────
        predicted_class = 1 if prob_ai > prob_real else 0
        cam = self.grad_cam.generate(input_tensor, target_class=predicted_class)

        # Resize CAM to original image size
        cam_resized = cv2.resize(cam, (image.shape[1], image.shape[0]))
        cam_uint8 = (cam_resized * 255).astype(np.uint8)
        cam_colored = cv2.applyColorMap(cam_uint8, cv2.COLORMAP_JET)
        vis = overlay_heatmap(image, cam_colored, alpha=0.4)

        # ── Score & verdict ─────────────────────────────────────────────
        if self._trained:
            score = prob_ai
            confidence = max(prob_real, prob_ai)
            detection_mode = "trained_model"
        else:
            # Fallback: use features as heuristic indicators
            score = self._fallback_analysis(image, prob_ai)
            confidence = 0.4  # Lower confidence for fallback
            detection_mode = "pretrained_fallback"

        # ── Flags ───────────────────────────────────────────────────────
        flags = []
        if score > AI_CONFIDENCE_THRESHOLD:
            flags.append(f"Image classified as AI-generated ({score:.1%} confidence)")
        else:
            flags.append(f"Image classified as real photograph ({1 - score:.1%} confidence)")

        if not self._trained:
            flags.append("⚠ Using pretrained features (no fine-tuned model available). Train for better accuracy.")

        return AnalysisResult(
            module_name=self.name,
            display_name=self.display_name,
            description=self.description,
            score=score,
            confidence=confidence,
            verdict="AI-Generated" if score > AI_CONFIDENCE_THRESHOLD else "Authentic",
            details={
                "probability_real": round(prob_real, 4),
                "probability_ai_generated": round(prob_ai, 4),
                "predicted_class": "ai_generated" if predicted_class == 1 else "real",
                "detection_mode": detection_mode,
                "model_architecture": "EfficientNet-B0",
                "input_size": AI_INPUT_SIZE,
            },
            visualization_b64=image_to_base64(vis),
            flags=flags,
        )

    def _fallback_analysis(self, image: np.ndarray, model_prob: float) -> float:
        """
        Heuristic analysis when no trained model is available.
        AI-generated images tend to have:
            - Smoother textures (lower high-frequency energy)
            - More uniform color distributions
            - Specific noise patterns
        """
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY).astype(np.float64)

        # High-frequency energy (Laplacian variance)
        laplacian_var = cv2.Laplacian(gray, cv2.CV_64F).var()

        # Texture smoothness indicator
        texture_score = 1.0 / (1.0 + laplacian_var / 500)

        # Color histogram uniformity
        hist_scores = []
        for ch in range(3):
            hist = cv2.calcHist([image], [ch], None, [64], [0, 256])
            hist = hist.flatten() / hist.sum()
            entropy = -np.sum(hist[hist > 0] * np.log2(hist[hist > 0]))
            hist_scores.append(entropy)
        avg_entropy = np.mean(hist_scores)
        entropy_score = max(0, 1 - avg_entropy / 6)  # Lower entropy = more AI-like

        # Combine heuristics with model output
        heuristic_score = texture_score * 0.4 + entropy_score * 0.3 + model_prob * 0.3
        return min(1.0, heuristic_score)
